"""Data preprocessing and ETL pipeline components."""

from src.preprocessing.cleaner import (
    DEFAULT_MISSING_TOKEN,
    INVALID_GENDERS,
    TERMINAL_DISCHARGE_DISPOSITION_IDS,
    clean_patient_records,
    filter_invalid_demographics,
    filter_terminal_discharges,
    replace_missing_tokens,
)
from src.preprocessing.encoder import (
    CHANGE_ACTIVE_STATUS,
    DIABETES_MED_ACTIVE_STATUS,
    INSULIN_ACTIVE_STATUSES,
    encode_age_midpoint,
    encode_diabetes_med_flag,
    encode_features,
    encode_insulin_flag,
    encode_medication_change_flag,
    encode_readmission_target,
    parse_age_bracket_midpoint,
)
from src.preprocessing.pipeline import (
    build_spark_session,
    run_preprocessing_pipeline,
)
from src.preprocessing.validators import (
    EXPECTED_RAW_COLUMNS,
    REQUIRED_CLEAN_COLUMNS,
    DataIntegrityError,
    SchemaValidationError,
    ValidationError,
    validate_age_range,
    validate_binary_flags,
    validate_cleaned_dataframe,
    validate_input_columns,
    validate_no_terminal_discharges,
    validate_output_columns,
    validate_target_values,
)

__all__ = [
    "DEFAULT_MISSING_TOKEN",
    "INVALID_GENDERS",
    "TERMINAL_DISCHARGE_DISPOSITION_IDS",
    "INSULIN_ACTIVE_STATUSES",
    "CHANGE_ACTIVE_STATUS",
    "DIABETES_MED_ACTIVE_STATUS",
    "EXPECTED_RAW_COLUMNS",
    "REQUIRED_CLEAN_COLUMNS",
    "ValidationError",
    "SchemaValidationError",
    "DataIntegrityError",
    "clean_patient_records",
    "filter_terminal_discharges",
    "filter_invalid_demographics",
    "replace_missing_tokens",
    "parse_age_bracket_midpoint",
    "encode_age_midpoint",
    "encode_insulin_flag",
    "encode_medication_change_flag",
    "encode_diabetes_med_flag",
    "encode_readmission_target",
    "encode_features",
    "validate_input_columns",
    "validate_output_columns",
    "validate_target_values",
    "validate_age_range",
    "validate_binary_flags",
    "validate_no_terminal_discharges",
    "validate_cleaned_dataframe",
    "build_spark_session",
    "run_preprocessing_pipeline",
]
